name: Pylint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache conda environment
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('CITEgeist_env.yml') }}

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda,defaults
        channel-priority: flexible

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env update --file CITEgeist_env.yml --name base
        pip install pylint

    - name: Analysing the CITEgeist folder with pylint
      shell: bash -l {0}
      run: |
        pylint CITEgeist --exit-zero --max-line-length=120 --disable=C0103,C0114,C0115,C0116
      continue-on-error: true
